In [1]:
from bqplot import (
    LinearScale,
    Axis,
    Figure,
    OrdinalScale,
    LinearScale,
    Bars,
    Lines,
    Scatter,
)

In [6]:
import numpy as np

x = np.linspace(-10, 10, 100)
y = np.sin(x)

# 1. Create the scales
xs = LinearScale(min=-10, max = 410)
ys = LinearScale()

# 2. Create the axes for x and y
xax = Axis(scale=xs, label="X")
yax = Axis(scale=ys, orientation="vertical", label="Y")

# 3. Create a Lines mark by passing in the scales
# note that Lines object is stored in `line` which can be used later to update the plot
line = Lines(x=x, y=y, scales={"x": xs, "y": ys})

# 4. Create a Figure object by assembling marks and axes
fig = Figure(marks=[line], axes=[xax, yax], title="Simple Line Chart")

# 5. Render the figure using display or just as is
fig

Figure(axes=[Axis(label='X', scale=LinearScale(max=410.0, min=-10.0)), Axis(label='Y', orientation='vertical',…

In [7]:
x = np.arange(10)

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x2 = np.reshape(x, (2, 5))

In [10]:
x2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
np.roll(x2, -1, axis=1)

array([[1, 2, 3, 4, 0],
       [6, 7, 8, 9, 5]])

In [13]:
x2[1:]

array([[5, 6, 7, 8, 9]])

In [14]:
N = 10
data = np.array(np.zeros((N,3)))

In [15]:
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
data[-1,:] = (1,2,3)

In [17]:
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.]])

In [18]:
data = np.roll(data, -1, axis = 0)

In [19]:
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.],
       [0., 0., 0.]])